server:
  port: 8090
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://logu.com:8761/eureka 

spring:
  datasource:
    #Connection url for the database "app"
    url: jdbc:mysql://localhost:3306/app
    # Username and password
    username: root
    password: root
    # Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1 
    
  # Show or not log for each sql query
  jpa:
    show-sql: true
    # Hibernate ddl auto (create, create-drop, update): with "update" the database
    # schema will be automatically updated accordingly to java entities found in
    # the project
    hibernate:
      ddl-auto: update  
      # Naming strategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect    
        
logging:
  level:
    root: info